version: '3'

services:
  cache:
    image: redis:3.2

  web:
    image: mozilla/iprepd
    volumes:
      - ${PWD}/test/iprepd.yaml:/app/iprepd.yaml
    links:
      - cache
    expose:
      - "8080"
    command: bin/iprepd

  test:
    image: node:12-alpine
    environment:
      - IPREPD_ADDR=web:8080
    links:
      - web
    volumes:
      - ${PWD}:/ip-reputation-js-client-test
    working_dir: /ip-reputation-js-client-test
    command: npm test

  web-ci:
    build:
      context: test/
    links:
      - cache
    expose:
      - "8080"

  test-ci:
    build:
      context: .
    environment:
      - IPREPD_ADDR=web-ci:8080
    links:
      - web
    command: npm test
